import { useRoute } from "wouter";
import { useReport } from "@/hooks/use-reports";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  ArrowLeft,
  Printer,
  ShieldCheck,
  Clock,
  FileText,
  AlertCircle,
  Lock,
  Eye,
  CheckCircle2,
  Bot,
} from "lucide-react";
import { Link } from "wouter";
import { Loader2 } from "lucide-react";
import { format } from "date-fns";
import { useState } from "react";
import { FirDocument } from "@/components/fir-document";

export default function ReportDetails() {
  const [, params] = useRoute("/report/:id");
  const id = params ? parseInt(params.id) : 0;
  const { data: report, isLoading } = useReport(id);
  const [activeTab, setActiveTab] = useState<"report" | "response">("report");

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-[60vh]">
        <Loader2 className="w-10 h-10 text-primary animate-spin" />
      </div>
    );
  }

  if (!report) {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh] space-y-4">
        <h2 className="text-2xl font-bold">Report Not Found</h2>
        <Link href="/dashboard">
          <Button>Back to Dashboard</Button>
        </Link>
      </div>
    );
  }

  const structured = report.structuredReport as any;
  const reportDate = report.createdAt
    ? format(new Date(report.createdAt), "PPP")
    : "N/A";
  const reportTime = report.createdAt
    ? format(new Date(report.createdAt), "p")
    : "";

  return (
    <div className="max-w-5xl mx-auto space-y-8 pb-12">
      {/* ── Hidden Print Area ── rendered off-screen, visible only when printing ── */}
      <div id="fir-print-area" style={{ display: "none" }}>
        <FirDocument
          title={report.title || "Cyber Incident Investigation Report"}
          reportId={report.id}
          generatedAt={
            report.createdAt
              ? new Date(report.createdAt).toISOString()
              : undefined
          }
          structuredReport={structured}
          rawDescription={report.rawDescription}
        />
      </div>

      {/* ── Page Header ── */}
      <div className="flex items-center gap-4 mb-8">
        <Link href="/dashboard">
          <Button variant="ghost" size="icon" className="rounded-full">
            <ArrowLeft className="w-5 h-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-2xl font-bold">{report.title}</h1>
          <div className="flex items-center gap-3 text-sm text-muted-foreground mt-1">
            <span className="flex items-center gap-1">
              <Clock className="w-3.5 h-3.5" /> {reportDate} {reportTime}
            </span>
            <span>•</span>
            <span className="flex items-center gap-1">
              <ShieldCheck className="w-3.5 h-3.5" /> ID: #{report.id}
            </span>
          </div>
        </div>
        <div className="ml-auto flex gap-3">
          <Button
            variant="outline"
            className="gap-2"
            onClick={() => {
              const el = document.getElementById("fir-print-area");
              if (el) el.style.display = "block";
              window.print();
              if (el) el.style.display = "none";
            }}
          >
            <Printer className="w-4 h-4" /> Print Report
          </Button>
        </div>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          <Card className="p-8 shadow-sm border-t-4 border-t-primary">
            <div className="flex items-center justify-between mb-8 pb-6 border-b border-border/50">
              <div>
                <h2 className="text-xl font-bold font-display uppercase tracking-wider text-primary">
                  Cyber Incident Investigation Report
                </h2>
                <p className="text-sm text-muted-foreground mt-1">
                  Generated by CyberDesk AI
                </p>
              </div>
              <Badge variant="outline" className="px-3 py-1 text-sm font-mono">
                {structured?.classification?.severity ||
                  structured?.executiveSummary?.severityLevel ||
                  structured?.incidentType}
              </Badge>
            </div>

            <div className="space-y-8">
              <FirDocument
                title={report.title || "Cyber Incident Investigation Report"}
                reportId={report.id}
                generatedAt={
                  report.createdAt
                    ? new Date(report.createdAt).toISOString()
                    : undefined
                }
                structuredReport={structured}
                rawDescription={report.rawDescription}
              />
            </div>
          </Card>
        </div>

        <div className="space-y-6">
          <Card className="p-6 bg-secondary text-secondary-foreground">
            <h3 className="font-bold mb-2">Next Steps</h3>
            <p className="text-sm text-secondary-foreground/80 mb-4">
              Submit this report to your local police station or the National
              Cyber Crime Portal.
            </p>
            <Link href="/chat">
              <Button
                variant="secondary"
                className="w-full bg-white text-secondary hover:bg-white/90"
              >
                Help me with filing
              </Button>
            </Link>
          </Card>

          <Card className="p-6 bg-card border-l-4 border-l-primary shadow-sm">
            <h3 className="font-bold text-lg mb-4">Why this matters?</h3>
            <p className="text-sm text-muted-foreground mb-4">
              Structured response helps reduce further loss and ensures that
              digital evidence is preserved for investigation.
            </p>
            <Link href="/chat">
              <Button className="w-full gap-2">
                <Bot className="w-4 h-4" /> Ask personal guidance
              </Button>
            </Link>
          </Card>
        </div>
      </div>
    </div>
  );
}
